### ISSUE TITLE
$apply() function should be called safely

### ISSUE THREAD

**Issue by TheHalcyonSavant** [lgalfaso/angular-dynamic-locale#61] opened 2015-06-10 07:04 UTC
I'm getting `Error: [$rootScope:inprog] $digest already in progress` in FF. I'm using angular v1.3.14. I assume you have forgotten `if (!$scope.$$phase)` before calling $apply [here](https://github.com/lgalfaso/angular-dynamic-locale/blob/master/src/tmhDynamicLocale.js#L128) and [here](https://github.com/lgalfaso/angular-dynamic-locale/blob/master/src/tmhDynamicLocale.js#L136).

Do you get the same problem in FF?

**Comment by lgalfaso** [comment] 2015-06-19 14:41
`loadScript` calls the callbacks using the browser `script.onload` (`var script = document.createElement('script')`.) So unless something is fiddling with the browser element creation functions or `onload` to add them within a `$digest`, this should not be possible.

Can you create a plunker that shows this issue?

**Comment by mllrjb** [comment] 2015-06-19 20:43
I'm having a similar intermittent issue when running a large test suite with Karma. Making @TheHalcyonSavant's change fixes the problem for me.

**Comment by lgalfaso** [comment] 2015-06-19 20:53
Without a way to reproduce this, it is somehow hard to know what is the root cause. Now, I *think* it is this Firefox issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1127236
https://bugzilla.mozilla.org/show_bug.cgi?id=354347
as outlined here https://github.com/angular/angular.js/issues/10083

If this is the case, then there is nothing for this library nor angular to do. Firefox must never have two threads running on the same stack.

**Comment by mllrjb** [comment] 2015-06-19 20:56
I'm seeing it using Karma + PhantomJS. I'll see if I can cobble together a test suite from a project.

**Comment by mllrjb** [comment] 2015-06-19 21:44
@lgalfaso - I'm having a difficult time reproducing a simple test suite that can reproduce the issue... I'd be happy to do a screen share and show you what I'm seeing in our project space. Any chance you'd be willing to merge this as a best-practice (and no-known side effects) without a test suite?

**Comment by lgalfaso** [comment] 2015-06-19 21:49
The property `$$phase` is private, that means that the patch as is without a test that is able to show the error, is not going to get merged.

**Comment by mllrjb** [comment] 2015-06-19 22:47
More digging (in case anybody else is interested). When it fails, I see a `$digest` begin and clear, but when your library invokes `$apply`, it fails because the `$rootScope.$$phase = '$digest'` still... Very odd. Across all browsers w/ Karma that I've tested. Will keep digging, but if anybody has ideas...

**Comment by mllrjb** [comment] 2015-06-19 22:51
@lgalfaso - I changed the `$rootScope.$apply` in the error handler to user `$rootScope.$applyAsync` and it appears to work fine. Would that be an acceptable solution without a test suite?

**Comment by nomve** [comment] 2015-09-01 10:42
I also have this issue when I'm using ng-show inside of a directive's template. It's really hard to reproduce because it happens on maybe 5% of first loads. At first I thought the problem was changing the variable used for ng-show, but actually just defining ng-show in the directive template causes this. Like I said it's difficult to reproduce, but since I've changed to $applyAsync it doesn't happen. I cannot guarantee that it's not an accident.

Here's the stack trace when it does happen
```
Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.18/$rootScope/inprog?p0=%24apply
minErr/<@http://tosa.intra/assets/libs/angular/angular.js:63:12
beginPhase@http://tosa.intra/assets/libs/angular/angular.js:14906:1
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://tosa.intra/assets/libs/angular/angular.js:14650:11
loadLocale/<@http://tosa.intra/assets/libs/angular-dynamic-locale/src/tmhDynamicLocale.js:128:9
loadScript/script.onload@http://tosa.intra/assets/libs/angular-dynamic-locale/src/tmhDynamicLocale.js:56:9
getterFn@http://tosa.intra/assets/libs/angular/angular.js:12665:26
Parser.prototype.identifier@http://tosa.intra/assets/libs/angular/angular.js:12197:12
Parser.prototype.primary@http://tosa.intra/assets/libs/angular/angular.js:12096:17
Parser.prototype.unary@http://tosa.intra/assets/libs/angular/angular.js:12382:14
Parser.prototype.multiplicative@http://tosa.intra/assets/libs/angular/angular.js:12365:16
Parser.prototype.additive@http://tosa.intra/assets/libs/angular/angular.js:12356:16
Parser.prototype.relational@http://tosa.intra/assets/libs/angular/angular.js:12347:16
Parser.prototype.equality@http://tosa.intra/assets/libs/angular/angular.js:12338:16
Parser.prototype.logicalAND@http://tosa.intra/assets/libs/angular/angular.js:12329:16
Parser.prototype.logicalOR@http://tosa.intra/assets/libs/angular/angular.js:12320:16
Parser.prototype.ternary@http://tosa.intra/assets/libs/angular/angular.js:12300:16
Parser.prototype.assignment@http://tosa.intra/assets/libs/angular/angular.js:12281:16
Parser.prototype.expression@http://tosa.intra/assets/libs/angular/angular.js:12277:12
Parser.prototype.filterChain@http://tosa.intra/assets/libs/angular/angular.js:12233:16
Parser.prototype.statements@http://tosa.intra/assets/libs/angular/angular.js:12215:25
Parser.prototype.parse@http://tosa.intra/assets/libs/angular/angular.js:12072:17
$parse@http://tosa.intra/assets/libs/angular/angular.js:12789:32
$RootScopeProvider/this.$get</Scope.prototype.$watch@http://tosa.intra/assets/libs/angular/angular.js:13983:19
ngShowDirective</<.link@http://tosa.intra/assets/libs/angular/angular.js:24992:7
invokeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:8290:9
nodeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7800:1
compositeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7149:13
nodeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7795:1
compositeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7149:13
nodeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7795:1
compositeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7149:13
compositeLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7152:13
publicLinkFn@http://tosa.intra/assets/libs/angular/angular.js:7028:30
bootstrapApply/<@http://tosa.intra/assets/libs/angular/angular.js:1460:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://tosa.intra/assets/libs/angular/angular.js:14552:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://tosa.intra/assets/libs/angular/angular.js:14651:18
bootstrapApply@http://tosa.intra/assets/libs/angular/angular.js:1458:9
invoke@http://tosa.intra/assets/libs/angular/angular.js:4219:14
bootstrap/doBootstrap@http://tosa.intra/assets/libs/angular/angular.js:1456:1
bootstrap@http://tosa.intra/assets/libs/angular/angular.js:1476:1
angularInit@http://tosa.intra/assets/libs/angular/angular.js:1370:5
@http://tosa.intra/assets/libs/angular/angular.js:26427:5
jQuery.Callbacks/fire@http://tosa.intra/assets/libs/jquery/dist/jquery.js:3099:10
jQuery.Callbacks/self.fireWith@http://tosa.intra/assets/libs/jquery/dist/jquery.js:3211:7
.ready@http://tosa.intra/assets/libs/jquery/dist/jquery.js:3417:1
completed@http://tosa.intra/assets/libs/jquery/dist/jquery.js:3433:2
	

return logFn.apply(console, args);

```

**Comment by lgalfaso** [comment] 2015-09-01 16:52
@nomve this looks like another issue, but maybe related. Would it be possible to know the exact version that you are using? Also, can you check if this is reproducible with the current version (if this is what I suspect, then it should be possible)

**Comment by nomve** [comment] 2015-09-01 20:14
@lgalfaso I believe we're using the current version, but I can't check until tomorrow.

**Comment by lgalfaso** [comment] 2015-09-01 21:50
@nomve would it be possible that the locale is changed multiple times back-and-forward within the bootstrap?

**Comment by nomve** [comment] 2015-09-02 09:42
@lgalfaso it isn't. It's actually not really used because the locale is at the moment just set in a run block, and then never changed after that. It should eventually be available, but isn't right now. So angular is 1.3.18 and 0.1.27. I'll try to setup a case where it shows up.

**Comment by lgalfaso** [comment] 2015-09-02 10:19
While trying to reproduce this, I found and fixed another issue, but if you
can create a scenario that shows the problem, then I would like to fix this
issue too before cutting a new release.

**Comment by crisbeto** [comment] 2015-09-03 07:03
I haven't managed to reproduce this myself, but I've had logs from users on IE11 with an error pointing to https://github.com/lgalfaso/angular-dynamic-locale/blob/master/src/tmhDynamicLocale.js#L61. I'm not quite sure why it happens since the `callback` is wrapped in a `$timeout` which generally doesn't throw "in progress" errors.

**Comment by nomve** [comment] 2015-09-03 08:27
I've copied the whole build to another temp directory that I access through localhost, and the completely same build doesn't reproduce under a different URL. Normally I have a temp domain like something.dev. I've even directed localhost to the same directory where the build is normally made and it doesn't reproduce either. 

so tl;dr: I can't reproduce and it's one of those bizarre problems.

**Comment by psalchow** [comment] 2015-11-19 12:03
I face the same problem with angular 1.4.7 and angular-dynamic-locale 0.1.28.

    Error: [$rootScope:inprog] $digest already in progress
    http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24digest
    minErr/<@http://localhost:8080/bower_components/angular/angular.js:68:12
    beginPhase@http://localhost:8080/bower_components/angular/angular.js:16346:1
    $RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8080/bower_components/angular/angular.js:15780:9
    $RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8080/bower_components/angular/angular.js:16097:13
    loadLocale/<@http://localhost:8080/bower_components/angular-dynamic-locale/src/tmhDynamicLocale.js:150:9
    loadScript/script.onload@http://localhost:8080/bower_components/angular-dynamic-locale/src/tmhDynamicLocale.js:70:9
    ASTCompiler.prototype.compile@http://localhost:8080/bower_components/angular/angular.js:13322:1
    Parser.prototype.parse@http://localhost:8080/bower_components/angular/angular.js:14146:12
    $parse@http://localhost:8080/bower_components/angular/angular.js:14248:32
    initializeDirectiveBindings/<@http://localhost:8080/bower_components/angular/angular.js:8834:25
    forEach@http://localhost:8080/bower_components/angular/angular.js:350:11
    initializeDirectiveBindings@http://localhost:8080/bower_components/angular/angular.js:8801:7
    nodeLinkFn@http://localhost:8080/bower_components/angular/angular.js:8226:1
    ...

Unfortunately this error occurs only sometimes on page load. I haven't realized that it occurs during usage of the application.

**Closed** 2015-11-19 16:01 UTC

**Comment by lgalfaso** [comment] 2015-11-19 16:04
@psalchow would it be possible for you to try with the current version at HEAD? If this works as intended, then I will cut a new release just with this fix

**Comment by psalchow** [comment] 2015-11-20 07:18
Awesome! Thanks lgalfaso, that seems to fix the issue. At least in my case. Would be great if you could release this fix.
